apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp2
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp2
    spec:
      containers:
        - name: sampleapp 
          image: capodilacr.azurecr.io/sampleapp2
          ports:
          - containerPort: 80